### ISSUE TITLE
Too much complicated + isn't even working.

### ISSUE THREAD

**Issue by mrplayzorro** [DaRealRomz/roblox-jobid-join#4]

**Comment by DaRealRomz** [comment]
The extension does work and is really quite simple.

Say you are the developer of [Welcome to Bloxburg](https://www.roblox.com/games/185655149/Welcome-to-Bloxburg) and want to create a link to join a specific server. All you need to create that link is the server's job id. You can obtain it using [`game.jobId`](https://create.roblox.com/docs/reference/engine/classes/DataModel#JobId). Take the regular link of the game (https://www.roblox.com/games/185655149/Welcome-to-Bloxburg) and add `?serverJobId=` with the job id.

e.g. https://www.roblox.com/games/185655149/Welcome-to-Bloxburg?serverJobId=9134c999-91d5-4b52-9f0a-f7cbae67fe77

If you have the extension installed and you open this link, it should attempt to launch Roblox and result in an error when joining the server because this job id is not valid.

**Comment by DaRealRomz** [comment]
Stale for 2 weeks.
